### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by optozorax** [jrmuizel/raqote#109]
`point_size` is not considered in function `draw_text` when positions are made.

https://github.com/jrmuizel/raqote/blob/2f4a3f19dcddb25ae19e323c4af8ac98d86585fe/src/draw_target.rs#L699

And we get this when trying to draw 36 sized font:
![изображение](https://user-images.githubusercontent.com/18114381/72085452-e9fb4d80-3337-11ea-9b7c-4d0bd4a14893.png)

dumb fix:
```rust
start += font.advance(id).unwrap() * point_size / 24. / 96.;
```

**Comment by jrmuizel** [comment]
Thanks for reporting. I'll try to look at this soon.
