### ISSUE TITLE
Rasterization of complex images 10x slower than Cairo

### ISSUE THREAD

**Issue by Shnatsel** [jrmuizel/raqote#122]
Rendering the image from https://gitlab.gnome.org/GNOME/librsvg/-/issues/574 with resvg takes 10 seconds with Cairo backend and 30 seconds with Raqote backend on my machine (end-to-end, including SVG processing by resvg). It's a 2400 by 2650px SVG with map data. As far as I can tell it only has fill and stroke with no interesting features.

A quick `perf` run shows that most of the time is spent in `raqote::rasterizer::Rasterizer::rasterize` when called from fill and stroke routines.

**Comment by jrmuizel** [comment]
I had a look at this more closely. It looks like the bulk of the time in `rasterize()` is being spent in `insert_starting_edges()` the insertion sort here can be O(n^2) but even if I move the sorts with large counts to a separate function a lot of the time remains in `insert_starting_edges()`

**Comment by jrmuizel** [comment]
I figured out what the problem was here. It was dumb.

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/raqote/commit/9734d12488420bb001be3c741e6c4d7bfbecf289 improves the time it takes to rasterize that svg for me from 23 seconds to 6.5 seconds. Do you mind retesting?

**Comment by Shnatsel** [comment]
End-to-end rendering with resvg now takes 15 seconds with raqote vs 11 seconds with cairo. Most of the difference is gone!

Most of the time spent in `raqote` is now taken up by `__memset_avx2_unaligned_erms` called by `__libc_calloc` called by `raqote::draw_target::DrawTarget::fill`. Interactive profile with flamegraph is [here](https://profiler.firefox.com/public/f264b211c5aa9e1b0991168d48b33d7a5a315fcc/flame-graph/?globalTrackOrder=0&localTrackOrderByPid=9987-0~&thread=0&timelineType=stack&v=4).

**Comment by jrmuizel** [comment]
That's likely caused by `MaskSuperBlitter:new()` https://github.com/jrmuizel/raqote/blob/master/src/blitter.rs#L41. We currently allocate a Vec that's fill bounds height * width. We don't actually need it to be that big. We could do rasterization in chunks so that we're only allocating some maximum height. Another thing we can do is reuse the allocation.

**Comment by Shnatsel** [comment]
Reusing the allocation sounds good. For completeness, another possible approach is to reserve a vector with a certain capacity and append to it via `.extend()` or `.extend_from_slice()` instead of casting it to a slice and writing by index. This would bypass the need for initializing memory altogether.

**Comment by jrmuizel** [comment]
Turns out there was another mistake causing a performance problem. https://github.com/jrmuizel/raqote/commit/0b8d17c4d338df9aeb3c29af0c2a9b16ad22d4e2 fixes it. Can you try testing again?

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/raqote/commit/8891da82fd9b85d4c4df23b2704ec3d288d8810e will help too.

**Comment by jrmuizel** [comment]
With those two additional changes my rendering time goes down to 3.6ms

**Comment by Shnatsel** [comment]
Yup, on this image raqote is now faster than cairo! Thanks!
