### ISSUE TITLE
scaled small images

### ISSUE THREAD

**Issue by cztomsik** [jrmuizel/raqote#127]
I think there's some issue with scaling small images

It works fine with "big" images (when it's scaled down) and usually with small ones too but if it's let's say 2x2 pixels, it's very broken and it won't be fine until 50x50 px (but it gets bit better with each extra pixel)

```
const CHECKER_BOARD: [u8; 2 * 2 * 4] = [255, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255, 255, 255, 255, 255];
```

Weird thing is that "dest size" doesn't matter (as soon as it has to be scaled, it's broken)

![image](https://user-images.githubusercontent.com/3526922/79019000-8b7f7e80-7b75-11ea-8871-7ec861232bb1.png)

And here's how it's with 20x20 px image (black & white because I've created it in editor, saved as png and loaded it as sanity-check)
![image](https://user-images.githubusercontent.com/3526922/79019376-7fe08780-7b76-11ea-8aae-441fdcb15970.png)

Here's how I use it (I'm using raqote as test backend so I don't need to mess with gl for now but it's why `uv` is 0-1 and I need to multiply it)

```
RenderOp::FillRect(bounds, style) => {
            let path = {
                let mut pb = PathBuilder::new();
                pb.rect(bounds.a.x, bounds.a.y, bounds.width(), bounds.height());
                pb.close();
                pb.finish()
            };

            // fill style
            let source = match style {
                FillStyle::SolidColor(color) => Source::Solid((*color).into()),

                FillStyle::Texture(texture, uv) => {
                    let Texture { width, height, ref data } = textures[*texture];
                    let data = unsafe { std::slice::from_raw_parts(data.as_ptr() as *const u32, data.len() / 4) };

                    let (w, h) = (width as f32, height as f32);
                    let transform = Transform::create_translation((uv.a.x * w) - bounds.a.x, (uv.a.y * h) - bounds.a.y)
                        .post_scale((uv.width() * w) / bounds.width(), (uv.height() * h) / bounds.height());

                    Source::Image(Image { width, height, data }, ExtendMode::Pad, FilterMode::Nearest, transform)
                }

                _ => panic!("TODO: fill {:?}", style),
            };

            dt.fill(&path, &source, &DrawOptions::new());
        }
```

**Comment by cztomsik** [comment]
Hm, it has something to do with the 1px steps, the issue gradually disappears with bigger and bigger squares in checkerboard (in original image data)

2x2
![image](https://user-images.githubusercontent.com/3526922/79033350-dd43fb00-7bad-11ea-97c8-4fc0ca8861fb.png)

4x4
![image](https://user-images.githubusercontent.com/3526922/79033344-cbfaee80-7bad-11ea-80b7-e7e8c7c15c69.png)

8x8 is almost fine but it's still bit off
![image](https://user-images.githubusercontent.com/3526922/79033332-b5549780-7bad-11ea-936e-2f4f664f8516.png)

**Comment by jrmuizel** [comment]
I'm not sure I understand what's going wrong here. Is it possible for you to write a standalone example that shows the problem?

**Comment by cztomsik** [comment]
Here's repo where I've tried to isolate the issue https://github.com/cztomsik/raqote_scaling_issue

Try to uncomment various sizes to see how it gets better. I think it should always give the same result but it doesn't.


![image](https://user-images.githubusercontent.com/3526922/79041381-b4445a00-7bef-11ea-85f9-b181861bf0ce.png)

![out](https://user-images.githubusercontent.com/3526922/79041401-e2299e80-7bef-11ea-86f4-936bd38b81bd.png)

vs.

![out](https://user-images.githubusercontent.com/3526922/79041405-f2417e00-7bef-11ea-95d5-9dcaec4549a4.png)

**Comment by jrmuizel** [comment]
I think I understand what's going wrong here
