### ISSUE TITLE
How to fill DrawTarget with a color?

### ISSUE THREAD

**Issue by RazrFalcon** [jrmuizel/raqote#13]
Something like:

```
cairo_set_source_color(...);
cairo_paint(...);
```

**Comment by jrmuizel** [comment]
```rust
    let mut pb = PathBuilder::new();
    pb.rect(0., 0., width, height);
    dt.fill(
        &pb.finish(),
        &Source::Solid(SolidSource {
            r: 0x80,
            g: 0x80,
            b: 0,
            a: 0x80,
        }),
        Winding::NonZero,
    );
```

It probably makes sense to at least have a fillRect helper that does this.

**Comment by RazrFalcon** [comment]
>`pb.rect(0., 0., width, height);`

Oh, I was looking for this method in `DrawTarget`.

Anyway, I'm not sure how well it will work with anti-aliasing. I'm worrying that edges will be semitransparent.

**Comment by jrmuizel** [comment]
If you use integer coordinates for the rect there should be no anti-aliasing happening. See https://github.com/jrmuizel/raqote/blob/15ded2297db114db51697f65020ae733e6233540/src/tests.rs#L5

**Comment by jrmuizel** [comment]
You can use the `clear()` method for this now.
