### ISSUE TITLE
How to draw DrawTarget on DrawTarget?

### ISSUE THREAD

**Issue by RazrFalcon** [jrmuizel/raqote#14]
Does `raqote` has something like `QPainter`+`QImage` or `cairo_t`+`cairo_surface_t`? Or should I rely only on layers (which are not implemented yet?)?

**Comment by jrmuizel** [comment]
It's not great right now. You'd need to copy out the pixels from get_data() and construct an Image source and fill using that.

**Comment by jrmuizel** [comment]
It should be possible to avoid the copy now that `Image` borrows it's data. The implementation of `pop_layer` does this kind of thing.

**Comment by jrmuizel** [comment]
The `repeating_draw_image` test has an example of this.
