### ISSUE TITLE
Is Image working?

### ISSUE THREAD

**Issue by futurepaul** [jrmuizel/raqote#15]
The example is commented out in capabilities.rs. I can draw some pixels like this:

```
draw_target.fill(
            &path,
            &Source::Image(my_own_image, Transform2D::create_scale(1.0, 1.0)),
            Winding::EvenOdd,
    );
```

But they're not the right pixels, and I'm not sure if it's my fault or raqote's.

Thank you for this wonderful library btw! @cbrewster and I are [testing it out as a backend to piet](https://github.com/futurepaul/piet/tree/master/piet-raqote) and it really matches that use-case well (the cairo similarities definitely help).

**Comment by jrmuizel** [comment]
It should work, though it's only had very limited testing. You might need
to play around with the matrix for stuff to end up in the right place. I
was testing it with a 512x512 photo. I'll try to put together a better
sample this afternoon if I get the chance.

**Comment by futurepaul** [comment]
Turns out it was my fault! I was giving it a bad path.

**Comment by cbrewster** [comment]
With certain transforms we are hitting a panic:
Our transform is only translating and scaling, and the panic only occurs with some scale values (although I haven't found a pattern yet).

`thread 'main' panicked at 'attempt to subtract with overflow'`

https://github.com/jrmuizel/sw-composite/blob/6e7b7ac13bc6563f7b7bb8d659d62dc325b58163/src/lib.rs#L162

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/raqote/commit/c547a28d7443127a2cc9ce5b3df78f1f6ace95e3 may have fixed this. Can you still reproduce?

**Comment by futurepaul** [comment]
Yes, I can confirm this is working! Before we could only scale to 2.0. Thank you!
