### ISSUE TITLE
Plz bump `sw-composite` version to `0.7.14`

### ISSUE THREAD

**Issue by twitchyliquid64** [jrmuizel/raqote#163]
Im getting the dreaded 

```
thread 'main' panicked at 'attempt to add with overflow', /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/sw-composite-0.7.13/src/lib.rs:806:42
```

on debug, but it goes away with raqote patched to `0.7.14`. Presumably thanks to https://github.com/jrmuizel/sw-composite/pull/10.

Can the version be booped plz?

**Comment by jrmuizel** [comment]
Done.
