### ISSUE TITLE
Using external buffer for DrawTarget

### ISSUE THREAD

**Issue by l4l** [jrmuizel/raqote#166]
It seems for now raqote can only draw into a self-allocated buffer ([here](https://github.com/jrmuizel/raqote/blob/master/src/draw_target.rs#L366)). It would be nice, if it can support passing a buffer as an argument and draw into it. That's particularly useful for mmap-ed memory provided by some other entity, e.g. [on Wayland](https://wayland-book.com/surfaces/shared-memory.html).

**Comment by l4l** [comment]
I've taken a look at current implementation and I believe it should be possible to wrap buffer in [Cow-like structure](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7f45fae65c84843eae815be27b1d8ae1), which simply have a mutable access to the inner value (without cloning comparing to std::Cow). Although, this change breaks compatibility due to a lifetime parameter at `DrawTarget`.

**Comment by jrmuizel** [comment]
Yeah, I've wanted something like this, but was discouraged by having to leak the lifetime parameter into the DrawTarget api.

**Comment by l4l** [comment]
Another possible solution is an additional type with a lifetime, but that probably make some duplicated code.

**Comment by danieldg** [comment]
A method that may be better for upstreaming than adding a lifetime parameter is to just abstract out the buffer provider as a generic type parameter that defaults to Vec<u32>.   That means all existing users continue to work as-is, and anyone with a buffer can create DrawTarget<&[u32]> instead with a different constructor.

I might make a fork with this implemented sometime soon.
