### ISSUE TITLE
draw_image_at causes weird artifacts

### ISSUE THREAD

**Issue by l4l** [jrmuizel/raqote#167]
Clearing background and drawing image (with default options) produces weird result.

Only `clear(..)` is fine:

![bg](https://user-images.githubusercontent.com/5658339/101679298-3aab8700-3a70-11eb-9c83-8fb892c8bbfe.png)

Only `draw_image_at(..)` is also fine (though you may notice some problems at the edges):

![out](https://user-images.githubusercontent.com/5658339/101679369-52830b00-3a70-11eb-964b-de4788c3b7ac.png)

Both `clear(..)` and `draw_image_at(..)`:

![mixed](https://user-images.githubusercontent.com/5658339/101679502-82caa980-3a70-11eb-8eed-3903feb4cbd7.png)

Here's the whole bunch of images including original logo: [pics.zip](https://github.com/jrmuizel/raqote/files/5668294/pics.zip).

<details>
<summary>Source code</summary>

```rust
use std::fs::*;

use raqote::*;

fn main() {
    let mut dt = DrawTarget::new(128, 128);

    dt.clear(SolidSource {
        r: 0x80,
        g: 0x80,
        b: 0x80,
        a: 0xff,
    });

    let decoder = png::Decoder::new(File::open("photo.png").unwrap());
    let (info, mut reader) = decoder.read_info().unwrap();
    let mut buf = vec![0; info.buffer_size()];
    reader.next_frame(&mut buf).unwrap();

    let mut image: Vec<u32> = Vec::new();
    for i in buf.chunks(4) {
        image.push(
            (i[3] as u32) << 24 | ((i[0] as u32) << 16) | ((i[1] as u32) << 8) | (i[2] as u32),
        )
    }
    let bitmap = Image {
        width: info.width as i32,
        height: info.height as i32,
        data: &image[..],
    };

    dt.draw_image_at(0., 0., &bitmap, &Default::default());

    dt.write_png("out.png").unwrap();
}

```

</details>

**Comment by jrmuizel** [comment]
I haven't looked closely but I suspect this might be caused by the decoded png not being represented with premultiplied alpha.

**Comment by l4l** [comment]
Indeed, changing the loop body to:

```rust
let source = SolidSource::from_unpremultiplied_argb(i[3], i[0], i[1], i[2]);

image.push(
    (source.a as u32) << 24
        | (source.r as u32) << 16
        | (source.g as u32) << 8
        | (source.b as u32),
);
```

produces an expected result. So the issue can be closed, I guess?
