### ISSUE TITLE
Please publish a new release to crates.io

### ISSUE THREAD

**Issue by Nopey** [jrmuizel/raqote#203]
Downstream in https://github.com/servo/servo/pull/31278 (which depends on the merged but unreleased #200), I'd like to use a release version of raqote.

Mind releasing a new version to crates.io?

If it helps, raqote's CI pipeline will succeed when it next runs; this is because pathfinder_simd released 0.5.3 today, fixing the stdsimd compile error.

Thanks!

**Comment by jrmuizel** [comment]
Done. v0.8.4

**Comment by Nopey** [comment]
Perfect, thanks!
