### ISSUE TITLE
Text Transforms

### ISSUE THREAD

**Issue by cbrewster** [jrmuizel/raqote#27]
Currently text does not respect the current transform.

Example:
```rust
let font = SystemSource::new()
    .select_best_match(&[FamilyName::Serif], &Properties::new())
    .unwrap()
    .load()
    .unwrap();

dt.set_transform(&Transform::create_rotation(euclid::Angle::degrees(45.)));
dt.draw_text(
    &font,
    24.,
    "Hello",
    Point::new(0., 0.),
    &Source::Solid(SolidSource {
        r: 0,
        g: 0,
        b: 0xff,
        a: 0xff,
    }),
    &DrawOptions::new(),
);
```

**Comment by jrmuizel** [comment]
Yeah. This is sort of a limitation of font-kit. I'm going to try to fix it.

**Comment by cbrewster** [comment]
Is it possible to use a transform on the text mask, or will that just produce bad-looking text?

**Comment by jrmuizel** [comment]
I considered that as a temporary solution but it would need support for transforming a8 surfaces and right now we just brgra support.
