### ISSUE TITLE
Incorrect Text Positioning

### ISSUE THREAD

**Issue by cbrewster** [jrmuizel/raqote#28]
Raqote usually has a coordinate system where the top left corner of the image is `0, 0`. However, when positioning text, the bottom left corner of the image is `0, 0`.

**Comment by jrmuizel** [comment]
Are you on Mac?

**Comment by cbrewster** [comment]
Yes

**Comment by jrmuizel** [comment]
If so, then you're probably seeing https://github.com/pcwalton/font-kit/issues/43

**Comment by cbrewster** [comment]
This was fixed in font-kit
