### ISSUE TITLE
How should fill work for unclosed path?

### ISSUE THREAD

**Issue by futurepaul** [jrmuizel/raqote#29]
I expect both of these shapes to look the same:
```
  let mut pb = PathBuilder::new();
  pb.move_to(10.0, 10.0);
  pb.line_to(10.0, 110.0);
  pb.line_to(110.0, 110.0);
  pb.line_to(110.0, 60.0);
  
  //Finish without closing
  let path = pb.finish();
  
  draw_target.fill(&path, &blue, &DrawOptions::new());

  let mut pb = PathBuilder::new();
  pb.move_to(120.0, 10.0);
  pb.line_to(120.0, 110.0);
  pb.line_to(220.0, 110.0);
  pb.line_to(220.0, 60.0);

  //Close, then finish
  pb.close();
  let path = pb.finish();

  draw_target.fill(&path, &blue, &DrawOptions::new());
```
But instead I get this:
![test-raqote](https://user-images.githubusercontent.com/543668/57662958-c57f8380-75a6-11e9-9777-8ce3e405a7bf.png)

The shape on the left doesn't fill any higher than the last position of the pathbuilder unless I call close. Afaik these both look like the shape on the right with Cairo.

**Comment by jrmuizel** [comment]
Currently the results of filling unclosed shapes is undefined. I'm not sure yet where it makes the most sense to provide the implicit close that most APIs give you. For now, you could probably add the close() in the caller by maintaining some extra state in `shape_to_path`

**Comment by futurepaul** [comment]
Alright, will do.
