### ISSUE TITLE
Incorrect filling with alpha

### ISSUE THREAD

**Issue by RazrFalcon** [jrmuizel/raqote#35]
```
SolidSource {
    r: 0,
    g: 128,
    b: 0,
    a: 127,
}
```

Creates:

![out](https://user-images.githubusercontent.com/725494/57713475-38f2c500-767b-11e9-9875-85a9b1bd0fec.png)

**Comment by RazrFalcon** [comment]
Looks like UB, since sometimes it simply ignores the alpha.

**Comment by jrmuizel** [comment]
Solid source is currently specified in premultiplied form so r, g and b must less than or equal to a.

**Comment by RazrFalcon** [comment]
This should be documented and we should use some `Color` type abstraction.

**Comment by jrmuizel** [comment]
Definitely
