### ISSUE TITLE
How to create an SVG-like radial gradient?

### ISSUE THREAD

**Issue by RazrFalcon** [jrmuizel/raqote#56]
I have a center point, focal point and radius.

https://www.w3.org/TR/SVG11/pservers.html#RadialGradients

**Comment by jrmuizel** [comment]
You can use a two_circle radial gradient. Use the first point as the focal point, the first radius as 0, the second point as the center point and final radius as the radius.

**Comment by RazrFalcon** [comment]
Doesn't work:

```rust
use raqote::*;

fn main() {
    let mut dt = DrawTarget::new(200, 200);

    let mut pb = PathBuilder::new();
    pb.rect(0.0, 0.0, 200.0, 200.0);
    let path = pb.finish();

    let mut gradient = Source::new_two_circle_radial_gradient(
        Gradient {
            stops: vec![
                GradientStop {
                    position: 0.0,
                    color: 0xffffffff,
                },
                GradientStop {
                    position: 1.0,
                    color: 0xff000000,
                },
            ],
        },
        Point::new(0.5, 0.5),
        0.0,
        Point::new(0.5, 0.5),
        0.5,
        Spread::Pad,
    );

    if let raqote::Source::TwoCircleRadialGradient(_, _, _, _, _, _, ref mut transform) = gradient {
        let ts = Transform::row_major(160.0, 0.0, 0.0, 160.0, 20.0, 20.0).inverse().unwrap();
        *transform = transform.pre_mul(&ts);
    }

    dt.fill(&path, &gradient, &DrawOptions::new());

    dt.write_png("out.png").unwrap();
}
```

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">
    <radialGradient id="rg1" cx="0.5" cy="0.5" r="0.5" fx="0.5" fy="0.5">
        <stop stop-color="#ffffff" offset="0"/>
        <stop stop-color="#000000" offset="1"/>
    </radialGradient>
    <path fill="url(#rg1)" d="M 20 20 L 180 20 L 180 180 L 20 180 Z"/>
</svg>
```

Expected | Actual
--- | ---
![](https://user-images.githubusercontent.com/725494/58325744-6980ee80-7e33-11e9-8019-3ff0e54f532c.png) | ![](https://user-images.githubusercontent.com/725494/58325768-7998ce00-7e33-11e9-8d26-7921188728db.png)

**Comment by jrmuizel** [comment]
I accidentally broke this with my gradient precision change. I should have a fix in a couple of minutes.

**Comment by jrmuizel** [comment]
Should be fixed now.

**Comment by RazrFalcon** [comment]
It's better now, but not quite.

Radial gradient has a strange pattern/offset. Here is a diff with other applications:

![](https://user-images.githubusercontent.com/725494/58341252-7a8f2700-7e56-11e9-8b4a-614391c418ee.png)

Spread=Repeat makes it even more visible:

![](https://user-images.githubusercontent.com/725494/58341257-7ebb4480-7e56-11e9-9da5-67f8829f1060.png)

PS: ignore *resvg (Qt)*, it's actually raqote.

**Comment by jrmuizel** [comment]
This should be fixed by https://github.com/jrmuizel/raqote/commit/e7356eef2307217861d75153c2b28058d7bd902c

**Comment by RazrFalcon** [comment]
Distortion became less visible, but it still present.

**Comment by jrmuizel** [comment]
I believe this is fixed now.
