### ISSUE TITLE
Fix stroke seaming around line joins

### ISSUE THREAD

**Issue by jrmuizel** [jrmuizel/raqote#6]
The line joins currently meet at the mid point of the line. This likely causes some different rounding and we end up with a seam between the line and the line join. It might be possible to fix this by being more careful about rounding but it's probably easier to just make sure that we use lines that are the width of the entire stroke and not halfway.

**Comment by RazrFalcon** [comment]
Not sure if this is the same bug, but all curves are bit broken:

![1557863392](https://user-images.githubusercontent.com/725494/57727722-e3c6ab80-769a-11e9-8fc5-b0add1cb50bf.png)

As you can see, the curve has cracks in it.

Flattening in general a bit "blocky".
