### ISSUE TITLE
Which backend can be used to draw image on screen

### ISSUE THREAD

**Issue by killkrt** [jrmuizel/raqote#75]
Sorry to open an issue that is not a real issue, actually is a question, but I was not able to find a clear answer in the documentation or examples.

I am trying to find a good pure Rust library to write a simple UI toolkit for a little game, and I was looking for something fast, with few dependencies and with vector graphics support (I would like to write a toolkit that easy scale on different DPI monitors), so raqote seems to be a good candidate!

My questions are:
- Which are the supported backend to render a `DrawTarget` (or maybe `Image`) to a window? GFX? Piston Graphics?
- Is raqote using any hardware acceleration (or multi-core) in order to speed the rendering process?

Thank you.

**Comment by jrmuizel** [comment]
A quick reply for now: Drawing to a window isn't that well supported/documented yet.

In the mean time you can take a look at https://github.com/jrmuizel/raqote/pull/67 and https://github.com/cbrewster/raqote-win.

Raqote does not use any hardware acceleration (and has no current plans to). It also doesn't use multiple threads, though this is something that may happen in the future.

**Comment by killkrt** [comment]
Thank you for your reply.

So maybe, at this time, raqote is not yet ready to be used as fast realtime 2D vector graphics library.
Anyway I will keep an eye on it, it seems promising!

**Comment by parasyte** [comment]
FWIW, I added an example that shows using `raqote` to animate some vectors using `pixels`: https://github.com/parasyte/pixels/tree/master/examples/raqote-winit The example uses `winit` for window handling, input, and event loop.

**Comment by jiyinyiyong** [comment]
@parasyte tried the demo and worked, but when I tried it with my code copy, it failed. so weird, maybe dependency problem somewhere since not all deps are up-to-date...

**Comment by parasyte** [comment]
@jiyinyiyong I may be able to help you better if you open a ticket on the `pixels` issue tracker. The example in the main branch has dependencies pretty much up to date.

**Comment by jiyinyiyong** [comment]
@parasyte tried again with a fresh new project and it works. last time I tried it inside an existing project of mine, but I didn't preserve the code. probably trying later. I'll report to pixels if I could reproduce.
