### ISSUE TITLE
How is data encoded in DrawTarget::get_data_u8_mut?

### ISSUE THREAD

**Issue by GarkGarcia** [jrmuizel/raqote#76]
I'd like to know in which format is the output from `DrawTarget::get_data_u8_mut` encoded. Is it RGBA?

I'm asking because I need to convert a `DrawTarget` to an [`image::DynamicImage`](https://docs.rs/image/0.22.1/image/enum.DynamicImage.html) and I can't find any references to that in the docs.

Thanks!

**Comment by GarkGarcia** [comment]
My guess is it's BRGA, but still, this should be mentioned somewhere.

**Comment by jrmuizel** [comment]
Yep. It's BGRA on little endian. I'm adding a note to the docs now.
