### ISSUE TITLE
Specify a viewport

### ISSUE THREAD

**Issue by nifker** [jrmuizel/raqote#94]
I though it might be senseful to be able to specify a viewport, like in OpenGL or Vulkan. What do you think?

**Comment by jrmuizel** [comment]
I'd like to stick to an API that's similar to other 2d libraries. They all default to pixel based userspace. You can easily emulate a viewport by using DrawTarget::set_transform().

**Comment by nifker** [comment]
Ive just tested around a bit and when I want to add shearing in x direction(https://upload.wikimedia.org/wikipedia/commons/2/2c/2D_affine_transformation_matrix.svg)
I am getting an multiply with overflow in L351 in rasterizer.rs.

Example code:
`use raqote::*;
use euclid::Transform2D;

const WINDOW_SIZE: (usize, usize) = (920, 480);

fn create_viewport_transform(size: (usize, usize)) -> Transform{
	//Scale about origin
	let x_scale = 2./size.0 as f32;
	let y_scale = 2./size.1 as f32;
	//Translate coordinates
	const x_trans: f32 = -1.;
	const y_trans: f32 = -1.;
	//Shear in x direction
	let x_shear = (size.0 as f32).atan2(size.1 as f32);
	println!("{}", x_shear);
	Transform2D::column_major(x_scale, x_shear, x_trans, 0., y_scale, y_trans).inverse().unwrap()
}

fn main(){
	let transform = create_viewport_transform(WINDOW_SIZE);
	let mut obj = [[-0.2, -1.], [-0.45, -0.5], [-0.2, 0.]];
	let mut dt = DrawTarget::new(WINDOW_SIZE.0 as i32, WINDOW_SIZE.1 as i32);

	dt.set_transform(&transform);

	let mut path = PathBuilder::new();
    path.move_to(obj[0][0], obj[0][1]); 
	path.line_to(obj[1][0], obj[1][1]);
	path.line_to(obj[2][0], obj[2][1]);
	path.close();
	let p = path.finish();

	dt.fill(&p, &Source::Solid(SolidSource{r: 0xAA, g: 0xAA, b: 0x22, a: 0xFF}), 
							  &DrawOptions::default());
	dt.stroke(
		&p,
		&Source::Solid(SolidSource {
			r: 0x00,
			g: 0x00,
			b: 0x00,
			a: 0x00,
		}),
		&StrokeStyle::default(), 
		&DrawOptions::new()
	);
	dt.write_png("test.png").unwrap();
}

`

**Comment by nifker** [comment]
Or shall I create a new issue for the overflow?

**Comment by jrmuizel** [comment]
Best to create a new issue.

**Comment by jrmuizel** [comment]
Raqote has some issue some issues with geometry with large coordinates. In this case I suspect the transform that you're creating is incorrect as you're ending up with coordinates like `x = -59909.9688, y = 119.999985`

**Comment by nifker** [comment]
Ive just seen that I need to create two transforms, but neither raqote has a method to apply multiple transforms nor euclid lets me combine multiple transforms into one.

**Comment by jrmuizel** [comment]
euclid has `pre_transform` and `post_transform` methods.
