### ISSUE TITLE
Feature request: DrawTarget::write_png_to_memory

### ISSUE THREAD

**Issue by Maldela** [jrmuizel/raqote#95]
Hi!
I think a function for `DrawTarget` to write a png encoded image to a Vec<u8> would be useful.
Right now it only writes a png file to a given `Path` which is not helpful, if you want to use the data in your program.

**Comment by jrmuizel** [comment]
This seems reasonable. I might make it so it just takes a w: Write.

**Comment by Maldela** [comment]
Perfect

**Comment by Maldela** [comment]
Nevermind. I was just too stupid to use the raw data.
