### ISSUE TITLE
Change the size of a DrawTarget

### ISSUE THREAD

**Issue by nifker** [jrmuizel/raqote#97]
It would be more efficient it would be possible to change the size of a drawtarget and reuse it for later operations.

**Comment by jrmuizel** [comment]
This seems like a reasonable request. I may implement it by supporting an externally owned backing store though.

Can you elaborate some more on your use case so that I can better understand what you're looking for?

**Comment by nifker** [comment]
I want to render an image and draw it to the screen, clear it and rerender, etc. But I dont want to throw away the memory as it can just be extended and doesnt need to be allocated each time.

**Comment by nifker** [comment]
Ive just worked on it and will now create a MR.

**Comment by jrmuizel** [comment]
Fixed by #101
